import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { renderHtml } from "../src/output.js";
import { scanRepo } from "../src/scan.js";

test("renderHtml includes summary metrics and escapes key content", () => {
  const html = renderHtml({
    rootDir: "/tmp/demo",
    envExamplePath: "/tmp/demo/.env.example",
    envExampleFound: true,
    stats: {
      filesDiscovered: 8,
      filesScanned: 4,
      findings: 3,
      keys: 2,
      envExampleKeys: 1
    },
    keys: ["API_KEY", "URL<unsafe>"],
    envExampleKeys: ["API_KEY"],
    missingInEnvExample: ["URL<unsafe>"],
    unusedInRepo: [],
    findings: [
      {
        key: "URL<unsafe>",
        path: "src/app.js",
        line: 7,
        pattern: "js_process_env_dot"
      }
    ],
    skipped: []
  });

  assert.match(html, /<!doctype html>/i);
  assert.match(html, /Coverage 50%/);
  assert.match(html, /Missing 1/);
  assert.match(html, /URL&lt;unsafe&gt;/);
  assert.doesNotMatch(html, /URL<unsafe>/);
});

test("scanRepo report renders missing and unused sections into html", async () => {
  const tempRoot = await fs.mkdtemp(path.join(os.tmpdir(), "envscout-"));

  try {
    await fs.writeFile(
      path.join(tempRoot, "app.js"),
      "const token = process.env.API_TOKEN;\nconst region = process.env.AWS_REGION;\n",
      "utf8"
    );
    await fs.writeFile(
      path.join(tempRoot, ".env.example"),
      "AWS_REGION=us-east-1\nLEGACY_TOKEN=deprecated\n",
      "utf8"
    );

    const report = await scanRepo(tempRoot, {
      envExamplePath: path.join(tempRoot, ".env.example")
    });
    const html = renderHtml(report);

    assert.deepEqual(report.missingInEnvExample, ["API_TOKEN"]);
    assert.deepEqual(report.unusedInRepo, ["LEGACY_TOKEN"]);
    assert.match(html, /API_TOKEN/);
    assert.match(html, /LEGACY_TOKEN/);
    assert.match(html, /Generated by EnvScout/);
  } finally {
    await fs.rm(tempRoot, { recursive: true, force: true });
  }
});
